# Generated by Django 3.1.6 on 2021-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveytogroup',
            name='period',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='surveytouser',
            name='period',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
