# Generated by Django 3.1.6 on 2021-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210507_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytogroup',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveytogroup',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveytogroup',
            name='period',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveytouser',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveytouser',
            name='period',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
