# Generated by Django 3.1.6 on 2021-05-08 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20210507_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytouser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
