# Generated by Django 3.1.6 on 2021-05-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210508_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='user',
            new_name='users',
        ),
    ]
